---
title: "Scientific Reports Editors"
author: "Ben Best"
date: "November 4, 2015"
output:
  html_document:
    toc: yes
    toc_depth: 2
  pdf_document:
    toc: yes
  word_document: default
---

# Introduction

Need to find a list of relevant editors from this [Scientific Reports list of editors](http://www.nature.com/srep/about/editorial-board).

# Methods
Here's a list of relevant authors:

```{r}
library(dplyr)   # data.frame manipulation, %>%
library(stringr) # string manipulation for R
library(readr)   # read and write nicely
library(rvest)   # web scraping
library(DT)      # data table
#library(scholar)
#source('GScholarScraper_3.2.R')

url = 'http://www.nature.com/srep/about/editorial-board'

# get authors
a = read_html(url) %>%
  html_nodes('b') %>%
  html_text() %>%
  data.frame() %>%
  select_(name = '.') %>%
  mutate(
    i = row_number())

# get groups based on first of sections
a_env = a %>% 
  filter(
    i >= i[name=='Amir AghaKouchak'],
    i  < i[name=='Venugopal Achanta']) %>%
  mutate(group='env')
a_evo = a %>% 
  filter(
    i >= i[name=='Arhat Abzhanov'],
    i  < i[name=='Vineet Ahuja']) %>%
  mutate(group='eco')

# bind environmental and evolutionary
a = bind_rows(
  a_env,
  a_evo) %>%
  mutate(
    first = str_replace(name, '^(.*?) (.*)$', '\\1'),
    last  = str_replace(name, '^(.*?) (.*)$', '\\2')
  )
#write_csv(a, 'scientific-reports_authors-env-evo.csv')
```

# Results

```{r out, echo=F}
datatable(a)
#library(xtable)
#xtable(a[1:3,1:10])
```

## Fancy Plot

